[database]
url = "mongodb://REPLACE-ME"
name = "diddy"
collection_name = "party"

[ping]
address = "wadescan"
port = 3169
protocol_version = 767

[scanner]
interface_name = "eth0"

[purger.interval]
secs = 60
nanos = 0

[purger.timeout]
secs = 60
nanos = 0

[printer.interval]
secs = 5
nanos = 0

[sender]
umem_size = 30
complete_size = 26
tx_size = 26
