# Database secrets, try to not share these everywhere
[database]
# mongo URL
url = "mongodb://REPLACE-ME"
# mongoDB collection
name = "mcscanner"
collection_name = "servers"

# SLP scanner
[ping]
# server address/port for the SLP
address = "wadescan"
port = 3169
# protocol version
protocol_version = 767

# Scanner config
[scanner]
# The interface to scan over
interface_name = "eth0"
# The amount of time to wait after each scan, ideally same as the purger timeout
tick_interval = 10

# Purger, this will drop stale connections
[purger]
interval = 60  # drop every X seconds
timeout = 60   # drop stuff that's >X seconds old

# Printer, will show occasional debug output
[printer]
interval = 5 

# Sender
[sender]
umem_size = 30
complete_size = 26
tx_size = 26